version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
  php-fpm:
    container_name: php-fpm
    # php-fpmはデフォルトで 9000番ポートを expose しているためそれを使う
    build:
      context: ./php/php81
    volumes:
      - type: bind
        source: "./src"
        target: "/var/www/src/"
    environment:
      - DB_CONNECTION=mysql
      - DB_DATABASE=lenet
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=shibuya

  db:
    container_name: db
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=lenet
      - MYSQL_ROOT_PASSWORD=shibuya
      - TZ=Asia/Tokyo
    volumes:
      - "dbdata:/var/lib/mysql/"

volumes:
  dbdata:
