version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
executors:
  default:
    working_directory: ~/src
    docker:
      - image: circleci/buildpack-deps:stretch
commands:
  first_test:
    description: "デモ用のテスト"
    parameters:
      param1:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.param1 >>
jobs:
  build:
    executor:
      name: default
    steps:
      - setup_remote_docker
      - first_test
