version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
executors:
  default:
    working_directory: ~/src
    docker:
      - image: circleci/buildpack-deps:stretch
commands:
  first_test:
    description: "デモ用のテスト"
    parameters:
      param1:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.param1 >> && echo $(pwd) && ls -al
  unit_test:
    description: "ユニットテストの実行"
    steps:
      - run:
          name: phpunit
          shell: /bin/bash -Ceu -o pipefail
          command: ./.circleci/scripts/start_script.sh
          no_output_timeout: 3600
jobs:
  build:
    executor:
      name: default
    steps:
      - setup_remote_docker
      - checkout
      - first_test
      - unit_test
